# Generated by Django 4.1.1 on 2023-07-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_public_alter_comment_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='NULL', upload_to='images'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
